### ISSUE TITLE
Excluding sites doesn't work

### ISSUE THREAD

**Issue by void-arg** [guyht/vimari#84] opened 2017-03-11 06:31 UTC
I've tried excluding Youtube since vimari ruins it (I can't comment because the hotkeys override my typing), but it isn't working at all. I tried youtube.com, youtube.com/watch, https://youtube.com, and nothing works. Restarted my browser, too and it still didn't work. What's going on?

Edit: Tried google.com as well and nothing changed.

**Comment by run2xs** [comment] 2017-04-04 17:10
Same for me.  I downgraded to 1.11 so I could comment on YouTube videos and use Gmail again.

**Comment by simeg** [comment] 2017-12-03 21:05
I can confirm this setting works poorly, right now the exact URL is required which makes it useless for youtube since every video has an unique URL. Will try to fix this until next version.

**Comment by simeg** [comment] 2017-12-04 21:07
This is fixed and will be included in 1.13.0.

**Closed by simeg** 2017-12-04 21:07 UTC
Labels: bug
