### ISSUE TITLE
(shift+f) does not open in new tabs

### ISSUE THREAD

**Issue by prabhu-madanagopal** [guyht/vimari#96] opened 2018-03-27 21:41 UTC
link hints - open in new tabs behaves like regular link hints and does not open in new tabs.

Also t shortcut does not open new tabs.

**Comment by peteygao** [comment] 2018-04-04 17:48
Ditto on `shift+f` bug.

Opening a new tab is not supported by Vimari. The issue is that it's missing a feature entirely, not that `t` doesn't work.

**Comment by simeg** [comment] 2018-05-09 21:55
Hi,

This is a known bug and we have a fix for it in master. However, we cannot build the extension as none of the maintainers has an Apple Developer License. We're currently looking for someone to help us with this, so whenever we can get some help to build a new version of the extension this problem will be fixed.

I'm closing this as there's not action to be taken on it right now. Sorry for the inconvenience.

**Closed by simeg** 2018-05-09 21:55 UTC
